$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
language: en-US

import:
  - node_modules/@cspell/dict-de-de/cspell-ext.json

dictionaries:
  - custom-dictionary

dictionaryDefinitions:
  - name: custom-dictionary
    path: dictionary.txt
    addWords: true

overrides:
  - filename: content/documentation/external-resources.md
    language: en-US,de-DE
