$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
language: en-US

dictionaries:
  - custom-dictionary

dictionaryDefinitions:
  - name: custom-dictionary
    path: dictionary.txt
    addWords: true
