languageCode: en-us
title: tinylog 3
baseURL: https://tinylog.org/v3/
theme: tinylog-theme
timeZone: Europe/Berlin
disableHugoGeneratorInject: true
publishDir: ./public/v3

params:
  maxMajorVersion: 3
  stableVersion: 2.6.0-M1  # TODO: Replace with tinylog 3 version after first release
  previewVersion: 2.6.0-M1 # TODO: Replace with tinylog 3 version after first release
  size: 254403

permalinks:
  /documentation: /:filename
  /news: /:year/:month/:title

disableKinds:
  - taxonomy
  - term
  - RSS

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
